spring:
  application:
    name: alif
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/alif
    username: user
    password: password
  rabbitmq:
    host: localhost
    username: user
    password: password
  liquibase:
    change-log: /db/changelog-master.yaml
server:
  error:
    whitelabel:
      enabled: false